{
 "title": "Mautic exporter dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of leads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mautic_numLeads_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of leads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mautic_numLeads_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "leads"
    }
   ]
  },
  {
   "title": "Number of emails",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mautic_numEmails_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of emails",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mautic_numEmails_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "emails"
    }
   ]
  },
  {
   "title": "Number of campaigns",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mautic_numCampaigns_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of campaigns",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mautic_numCampaigns_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "campaigns"
    }
   ]
  },
  {
   "title": "Number of page hits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mautic_numPageHits_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of page hits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mautic_numPageHits_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "page hits"
    }
   ]
  },
  {
   "title": "Number of messages in queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mautic_numMessageQueue_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of messages in queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mautic_numMessageQueue_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Number of webhook in queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mautic_numWebhookQueue_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of webhooks in queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mautic_numWebhookQueue_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "webhooks"
    }
   ]
  }
 ]
}