name: Docker Image CI

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract git tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag mautic_exporter:$RELEASE_VERSION
    - name: Dockerhub login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USER} --password-stdin
    - name: Dockerhub Push
      run: |
        docker push ${DOCKER_USER}/mautic_exporter:$RELEASE_VERSION
