name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mautic_exporter:$(date +%s)
    - name: Dockerhub login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USER} --password-stdin
    - name: Dockerhub Push
      run: docker push $DOCKER_USER/mautic_exporter:$(date +%s)
